wdio.conf.js
=> Change logLevel

pageObjects/register.page.js
used waitForClickable({ timeout: 5000 })
=> TLC-254 Refactor Terms and Agreements

20602/specs/regression/register.spec.js, testData/user.js
- Created New, Learner, Student users in testData/user.js
- Moved login.spec.js and register.spec.js to Regression folder
- Created folders Smoke, Regression
=> TLC-310 Created New, Learner, Student users in testData/user.js

20608/specs/smoke/login.js, 20610/data/fakeData.js
=> TLC-334 // create smoke test/login.spec

20609/specs/regression/login.js
TLC-349 Add some regression test for Login page
=> TLC-349 Add some regression test for login.js

pageObjects/register.page.js
https://jira.pasv.us/browse/TLC-359
=> TLC-359 selector fixed 

20610/data/expected.json, 20610/specs/regression/registrationRegression.js
https://jira.pasv.us/browse/TLC-355
=> TLC-355 registration Regression from group 20610

20610/specs/smoke/loginSmoke.js
https://jira.pasv.us/browse/TLC-311
=> TLC-302 fixed (delete if statement since the issue was fixed)

20608/specs/regression/login.js
=> login regression TC

20610/data/expected.json, 20610/data/fakeData.js, 20610/specs/smoke/registrationStep2Smoke.js
https://jira.pasv.us/browse/TLC-364
=> TLC-364 user registration step2, smoke

20610/specs/smoke/registrationSmoke.js
https://jira.pasv.us/browse/TLC-365
=> TLC-365 Create full NewUser registration. Step2 added to new user registration.

20610/specs/smoke/loginSmoke.js
1.After each hook added
2.h1 check deleted
https://jira.pasv.us/browse/TLC-367
=> TLC-367 Login Smoke updated

pageObjects/settings.email.page.js
https://jira.pasv.us/browse/TLC-368
=> TLC-368 Add selector for "email" to settings.email.page.js

20606/specs/smoke/loginAdmin.page.spec.js
1. Add test-case number to the title;
2. Add expect result for admin role badge;
=> TLC-302 fixed

pageObjects/profile.page.js
https://jira.pasv.us/browse/TLC-380
=> TLC-380 profile.page.js one selector updated since a new element has been added

20610/specs/smoke/resetEmailSmoke.js
https://jira.pasv.us/browse/TLC-370
=> TLC-370 reset email for new user with success login

package-lock.json, package.json
https://jira.pasv.us/browse/TLC-381
=> TLC-381 Added axios to package.json + package-lock.json

20605/specs/smoke/login.js, 20605/specs/smoke/logout.js
autotests for Logout with different roles
autotest for Login as a NEW USER
=> TLC-336 added autotests for Logout(smoke)

helpers/deleteNewUserByAxios.js
https://jira.pasv.us/browse/TLC-397
=> Add method delete new User (by axios) to helpers.js file to POM

20610/specs/smoke/registrationSmoke.js
https://jira.pasv.us/browse/TLC-398
=> TLC-398 add delete method to registrationSmoke.js

20602/specs/regression/links.specs.js, pageObjects/profile.page.js
20602 > links.specs.js updated with Links input fields positive tests
Page.Object > profile.page.js selectors added
=> TLC-404 Create TC for social links positive inputs

20606/specs/smoke/register.page.spec.js, 20606/specs/smoke/register.skip.page.spec.js, 20606/testData/register_new.js
=> TLC 294 Register Page Smoke

pageObjects/contactUs.page.js
https://jira.pasv.us/browse/TLC-429
=> Adding selectors to contactUs.page.js (POM)

20610/specs/smoke/registrationStep2Smoke.js
https://jira.pasv.us/browse/TLC-428
=> TLC-428 add delete method to registrationStep2Smoke.js

20610/data/fakeData.js, 20610/specs/smoke/contactUsSmoke.js
https://jira.pasv.us/browse/TLC-430
=> contactUsSmoke.js is done, one last expect will be added later on

20610/data/fakeData.js
https://jira.pasv.us/browse/TLC-441
=> TLC-441 add shipping info to fakeData.js

20601/specs/smoke/topMenu.spec.js, 20609/specs/regression/loginLayout.js, pageObjects/topMenu.page.js
https://jira.pasv.us/browse/TLC-447
=> TLC-447 refactor selector name + add selector to topMenu

20608/data/homePage.data.json, 20608/data/login.data.json, 20608/specs/regression/login.js
=> add login regression tests, created homePage data and login data

20610/specs/regression/registrationRegression.js, helpers/clearValueMethod.js
https://jira.pasv.us/browse/TLC-460
=> TLC-460 Add function for clearValue to helpers

20602/data/expected.json, 20602/specs/regression/login.spec.js
- Updated login.page.js (20602)
- Added data to expected.json (20602)
=> TLC-426 Update login.page.js (20602)

20602/specs/regression/termsAndAgreements.js
Completed whale tests for Terms and Agreements (regression)
=> Terms and Agreements regression specs new tests

20610/specs/regression/contactUsRegression.js, 20610/specs/smoke/updatePassword.js
https://jira.pasv.us/browse/TLC-466
=> TLC-466 contactUs.page.js (regression testing) + add TEST CASES numbers to file updatePassword.js

20610/specs/smoke/dailyReportsSmoke.js
https://jira.pasv.us/browse/TLC-519
=> Adding axios check to dailyReportsSmoke.js + updating the file since the bug has been fixed

20610/data/expected.json, 20610/specs/smoke/contactUsSmoke.js, pageObjects/contactUs.page.js
+ one selector added to POM + group 610 expected.json has been updated
=> Updating ContactUsSmoke.js file (expect added) after a missing message was added by the developers team

20610/api/20610_collection, 20610/api/env20610.json
https://jira.pasv.us/browse/TLC-523
=> Adding api collection to 20610

hooks/afterHook.js, qa6_forCI/data/expected.json, qa6_forCI/helpers/faker.js, qa6_forCI/helpers/userDelete.js, qa6_forCI/helpers/userUpdateRole.js, qa6_forCI/smoke/homePage.js, qa6_forCI/smoke/loginUser.js, qa6_forCI/smoke/registrationUser.js, qa6_forCI/smoke/registrationUserStep2.js, qa6_forCI/smoke/updatePassword.js, qa6_forCI/smoke/updateShippingAdress.js, testData/user.js
https://jira.pasv.us/browse/TLC-551
=> TLC-551 tests for CI

20610/axiosTests/adminCourseCreationAxios.js, 20610/axiosTests/userLogin.js, 20610/axiosTests/userRegister.js, 20610/axiosTests/userUpdateRole.js
https://jira.pasv.us/browse/TLC-556
=> adminCourseCreationAxios.js updated + host url is added to axios tests

20610/specs/regression/contactUsRegression.js, 20610/specs/smoke/adminSearchSmoke.js, pageObjects/adminSearchForUsers.js
contactUs(regression) one it deleted since selector was modified by developers
https://jira.pasv.us/browse/TLC-557
=> adminSearchSmoke.js file added+ AdminSearchForUsers (POM) added + 
